// <auto-generated />
using System;
using Hackathon.VALIA.WEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackathon.VALIA.WEB.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191026114919_unificado_v1")]
    partial class unificado_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hackathon.VALIA.WEB.Models.Arquivo", b =>
                {
                    b.Property<int>("ArquivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LinhaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArquivoId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("Hackathon.VALIA.WEB.Models.Erros", b =>
                {
                    b.Property<int>("LinhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArquivoId")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoInicial")
                        .HasColumnType("int");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinhaId");

                    b.HasIndex("ArquivoId");

                    b.ToTable("Erros");
                });

            modelBuilder.Entity("Hackathon.VALIA.WEB.Models.Erros", b =>
                {
                    b.HasOne("Hackathon.VALIA.WEB.Models.Arquivo", null)
                        .WithMany("Erros")
                        .HasForeignKey("ArquivoId");
                });
#pragma warning restore 612, 618
        }
    }
}
